### ISSUE TITLE
rocon_hue timeout bug

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_devices#16]
```
[INFO] [WallTime: 1400051794.264950] Scheduler : compatibility tree is valid, attempting to allocate [b43397cf-9498-44d8-9b7b-11659da0dd10]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 45, in hue_checker
    if self.ping_checker():
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 67, in ping_checker
    self.ip = self.bridge.get_ip_address(set_result=True)
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/src/rocon_hue/phue.py", line 476, in get_ip_address
    result = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 430, in readline
    data = recv(1)
timeout: timed out

```

**Comment by jihoonl** [comment]
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 57, in hue_checker
    self.bulb_checker()
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 88, in bulb_checker
    if light.reachable:
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/src/rocon_hue/phue.py", line 275, in reachable
    self._reachable = self._get('reachable')
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/src/rocon_hue/phue.py", line 86, in _get
    return self.bridge.get_light(self.light_id, *args, **kwargs)
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/src/rocon_hue/phue.py", line 612, in get_light
    'GET', '/api/' + self.username + '/lights/' + str(light_id))
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/src/rocon_hue/phue.py", line 455, in request
    result = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 430, in readline
    data = recv(1)
timeout: timed out
```

**Comment by dwlee** [comment]
I fixed .
7f91f7d1dcf8f52da4219980816ba448c438bae4
