### ISSUE TITLE
[rocon_hue]Bad status line error

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_devices#22]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 45, in hue_checker
    if self.ping_checker():
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 71, in ping_checker
    urlopen(url, timeout=time_out)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

```

**Comment by 1337** [comment]
I have the same error in an unrelated code base with the same traceback. Did you find anything?

**Comment by dwlee** [comment]
The reason of this problem is that hue ip was not set in hue bridge.
Could you like to try to use indigo branch?

**Comment by 1337** [comment]
The problem was from unrelated code base. Thanks anyway.
