### ISSUE TITLE
[ros hue]Value error

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_devices#23]
```
Traceback (most recent call last):
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 164, in <module>
    rh = Rocon_Hue()
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/scripts/rocon_hue_bridge.py", line 28, in __init__
    self.ip = self.bridge.get_ip_address(set_result=True)
  File "/home/yujin/demos/rocon_demo_201405/src/rocon_devices/rocon_hue/src/rocon_hue/phue.py", line 491, in get_ip_address
    data = json.loads(result_str)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by dwlee** [comment]
This error is happened when the result of getting hue ip is null.

**Comment by dwlee** [comment]
I will change to parameter of hue ip instead of auto detecting.
